<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inptText_TextString</name>
   <tag></tag>
   <elementGuidId>49f9cb8f-2b18-41a2-8f91-6f20275336b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_text_string']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_text_string</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Submit me&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c28254a-4898-4a5d-bec3-76686378aa2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b436320d-bc69-4b01-9317-b2fd1d1eb379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>text_string</value>
      <webElementGuid>b42693b0-5c8e-4d30-ad67-a977794b6778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Submit me</value>
      <webElementGuid>ee9812c3-e4c8-466f-a393-ccab8a2a34f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textinput textInput form-control</value>
      <webElementGuid>0844f260-cf90-48ac-9ebc-adfdcb0b7484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_text_string</value>
      <webElementGuid>231c96bd-d332-4d3a-babd-bd95abb0c667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_text_string&quot;)</value>
      <webElementGuid>a3b49fcb-9670-4e2f-b35a-db9caeff523e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_text_string']</value>
      <webElementGuid>e973016b-f39b-4ef3-af3a-b6d205a8cb0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_id_text_string']/input</value>
      <webElementGuid>2511b4cc-51b8-49b1-b715-de9b8fb1b5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>2049cd7f-0b60-403a-a14b-1d20c18fa5fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'text_string' and @placeholder = 'Submit me' and @id = 'id_text_string']</value>
      <webElementGuid>5c1f776e-4ba9-4de6-b3b8-cebaf323dc0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
