<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_TextInput</name>
   <tag></tag>
   <elementGuidId>ae3677bf-c165-4077-be31-4bb7a50ec347</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/ol/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ol.rectangle > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Text input&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6070ca2c-0104-4df7-af90-3e9854616bfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/elements/input/simple</value>
      <webElementGuid>f771d63c-6892-4f21-a2b7-df11c1a0f4ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Text input</value>
      <webElementGuid>04630822-9413-4eb6-a205-3f37d0510a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;home&quot;]/ol[@class=&quot;rectangle&quot;]/li[1]/a[1]</value>
      <webElementGuid>cb8de87d-1554-40c6-a9e2-78ca7198005d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/ol/li/a</value>
      <webElementGuid>f9132f0b-e51b-4b78-90a4-974088c0c710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Text input')]</value>
      <webElementGuid>0a7b21fe-ba8a-4e11-95f8-cccaf04124b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello!'])[1]/following::a[1]</value>
      <webElementGuid>c2be7585-2ffd-4f27-81ad-18ad667b0efd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pop-Up'])[1]/following::a[1]</value>
      <webElementGuid>bdb8af0a-24ec-4da1-9e43-329db2a7fd48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simple button'])[1]/preceding::a[1]</value>
      <webElementGuid>7530c768-5d4a-48e4-8452-e52e8f082030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Single checkbox'])[1]/preceding::a[2]</value>
      <webElementGuid>c0680bb2-a0c6-48e4-ad25-c8298f543e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Text input']/parent::*</value>
      <webElementGuid>95c47841-1ebd-4c22-9c38-34b2db072f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/elements/input/simple')]</value>
      <webElementGuid>0eb9976a-b33e-4ac2-bb79-896f4061aad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li/a</value>
      <webElementGuid>e3be27a0-2d07-48a5-bb07-ff635a0647b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/elements/input/simple' and (text() = 'Text input' or . = 'Text input')]</value>
      <webElementGuid>e90393d3-811b-4c1a-916b-efd374a854e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
